version: '3.6'

services:
    db:
        hostname: postgres-lupinemoon
        image: postgres:11
        container_name: lupinemoon-local-postgres-db
        expose:
            - 5432
        ports:
            - 5434:5432
        volumes:
            - ./db-scripts:/docker-entrypoint-initdb.d
            - ./db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=lupinemoon
            - POSTGRES_USER=master
            - POSTGRES_PASSWORD=masterkey
