logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations
[web]
address = ":8080"

[api]
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  entryPoint = "api"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard = true

# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
# This will hide all docker containers that don't have explicitly
# set label to "enable"
exposedbydefault = false

[entryPoints]
  [entryPoints.api]
  address=":6564"

  [entryPoints.http]
  address = ":6565"
    # Force HTTPS
    # [entryPoints.http.redirect]
    # entryPoint = "https"

  [entryPoints.https]
  address = ":8143"
    [entryPoints.https.tls]

# Let's encrypt configuration
# [acme]
#   caServer = "https://acme-staging.api.letsencrypt.org/directory"
#   email = "letsencrypt@example.com"
#   storage="/etc/traefik/acme.json"
#   entryPoint="https"
#   acmeLogging=true
#   onDemand=true
#   OnHostRule=true
